import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Main from '../components/HomePage/Main';
import {Fragment} from 'react';
import Actualgrid from '../components/HomePage/Actual/Actualgrid';
import Cardgrid from '../components/Card/Cardgrid';
import Contactform from '../components/HomePage/Actual/Contactform';

const datacard = [
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
  {
    image: '/image/hoode.jpg',
    title: 'Burbery',
    description: 'парка с капюшоном и логотипом',
    price: '50$',
    slug: 1,
    size: 's',
    article: 2,
  },
];

const actualdata = [
  {image: '/image/hoode.jpg', title: 'Толстовки и худи'},
  {image: '/image/sneak.jpg', title: 'Кроссовки'},
  {image: '/image/coat.png', title: 'Верхняя одежда'},
  {image: '/image/under.jpg', title: 'Нижнее белью'},
];

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <Main></Main>
        {/* <Cardgrid cards={datacard}></Cardgrid> */}

        <Cardgrid cards={datacard}></Cardgrid>
        <Actualgrid actualdata={actualdata}></Actualgrid>
        <Contactform></Contactform>
      </Fragment>
      {console.log(datacard)}
    </div>
  );
}
