import Head from 'next/head';

import {Fragment} from 'react';

import Main from 'components/HomePage/Main';
import СategoriesGrid from 'components/HomePage/Сategories/СategoriesGrid';
import CardGrid from 'components/Card/CardGrid';
import ContactForm from 'components/HomePage/Contact/ContactForm';

import {connectToDatabase} from '../lib/db';

import styles from '../styles/Home.module.css';

export default function Home(props) {
  async function addEmailHandler(emailData) {
    const response = await fetch('/api/email', {
      method: 'POST',
      body: JSON.stringify(emailData),
      headers: {
        'Content-Type': 'aplication/json',
      },
    });
    const data = await response.json();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <Main></Main>
        <CardGrid cards={props.datacard}></CardGrid>
        <СategoriesGrid actualdata={props.actualdata}></СategoriesGrid>
        <ContactForm addEmail={addEmailHandler}></ContactForm>
      </Fragment>
    </div>
  );
}

export async function getStaticProps() {
  const client = await connectToDatabase();
  const db = client.db();

  const goodsCollection = db.collection('goods');
  const datacard = await goodsCollection.find().toArray();
  const mainCollection = db.collection('main');
  const main = await mainCollection.find().toArray();
  client.close();

  return {
    props: {
      datacard: datacard.map((datacard) => ({
        image: datacard.image,
        title: datacard.title,
        description: datacard.description,
        price: datacard.price,
        slug: datacard.slug,
        size: datacard.size,
        article: datacard.article,
        id: datacard._id.toString(),
      })),
      actualdata: main.map((main) => ({
        image: main.image,
        title: main.title,
      })),
    },
    revalidate: 1,
  };
}
