import Head from 'next/head';

import {MongoClient} from 'mongodb';
import {Fragment} from 'react';

import Main from '../components/HomePage/Main';
import СategoriesGrid from '../components/HomePage/Сategories/СategoriesGrid';
import Cardgrid from '../components/Card/Cardgrid';
import Contactform from '../components/HomePage/Contact/Contactform';

import styles from '../styles/Home.module.css';
import {connectToDatabase} from '../lib/db';

export default function Home(props) {
  async function addEmailHandler(emailData) {
    const response = await fetch('/api/email', {
      method: 'POST',
      body: JSON.stringify(emailData),
      headers: {
        'Content-Type': 'aplication/json',
      },
    });
    const data = await response.json();
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Fragment>
        <Main></Main>
        <Cardgrid cards={props.datacard}></Cardgrid>
        <СategoriesGrid actualdata={props.actualdata}></СategoriesGrid>
        <Contactform addEmail={addEmailHandler}></Contactform>
      </Fragment>
    </div>
  );
}

export async function getStaticProps() {
  const client = await MongoClient.connect(
    'mongodb+srv://vit:qwerty123@cluster0.6sdaa.mongodb.net/goods?retryWrites=true&w=majority',
  );
  const db = client.db();

  const goodsCollection = db.collection('goods');
  const datacard = await goodsCollection.find().toArray();
  const mainCollection = db.collection('main');
  const main = await mainCollection.find().toArray();
  client.close();

  return {
    props: {
      datacard: datacard.map((datacard) => ({
        image: datacard.image,
        title: datacard.title,
        description: datacard.description,
        price: datacard.price,
        slug: datacard.slug,
        size: datacard.size,
        article: datacard.article,
        id: datacard._id.toString(),
      })),
      actualdata: main.map((main) => ({
        image: main.image,
        title: main.title,
      })),
    },
    revalidate: 1,
  };
}
